public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");

        Variable variable = new Variable();
        System.out.println(variable.printResult());
        variable.printResult1();
        System.out.println(variable.printResult2());
        variable.printResult3(25.0, 5.0);
        variable.printResult4();
        variable.printResult5(30, 50, 30);
        System.out.println("ЗАдача 1");
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog+ ", " +cat+ ", " + paper);
        System.out.println("Задача 1 выполнена");
        System.out.println("Задача 2");
        dog =  dog +4;
        cat = cat +4;
        paper = paper +4;
        System.out.println(dog+ ", " +cat+ ", " + paper);
        System.out.println("Задача 2 выполнена");
        System.out.println("Задача 3");
        dog =  dog - 3.5;
        cat = cat - 1.6;
        paper = paper - 7639;
        System.out.println(dog+ ", " +cat+ ", " + paper);
        System.out.println("Задача 3 выполнена");
        System.out.println("Задача 4");
        var friend = 19;
        System.out.println(friend);
        friend = friend+2;
        System.out.println(friend);
        friend=friend/7;
        System.out.println(friend);
        System.out.println("Задача 4 выполнена");
        System.out.println("Задача 5");
        var frog = 3.5;
        System.out.println(frog);
        frog = frog*10;
        System.out.println(frog);
        frog = frog/3.5;
        System.out.println(frog);
        frog = frog+4;
        System.out.println(frog);
        System.out.println("Задача 5 выполнена");
        System.out.println("Задача 6");
        var boxer1 = 78.2;
        var boxer2 = 82.7;
        var boxerAverageWeight = (boxer1+boxer2)/2;
        System.out.println(boxerAverageWeight);
        System.out.println("Задача 6 выполнена");
        System.out.println("Задача 7");
        var weight1 = 78.2;
        var weight2 = 82.7;
        var devisionWeight = weight2%weight1;
        System.out.println(devisionWeight);
        System.out.println("Задача 7 выполнена");
        System.out.println("Задача 8");
        var workTime = 640;
        var employeeHour = 8;
        var totalEmployee = workTime/employeeHour;
        System.out.println("Всего работников в компании — " + totalEmployee + " человек");
        totalEmployee = totalEmployee+94;
        workTime = totalEmployee*employeeHour;
        System.out.println("Если в компании работает " + totalEmployee + " человек, то всего " + workTime + " часа работы может быть поделено между сотрудниками");
        System.out.println("Задача 8 выполнена");
        System.out.println("Домашняя работа ПЕРЕМЕННЫЕ выполнена");
    }

}